### ISSUE TITLE
Switching User Agent does not wotk anymore

### ISSUE THREAD

**Issue by Aftergit** [macchrome/droidchrome#33] opened 2023-09-30 16:01 UTC
On builds v117.5938 switching user agent to display desktop or mobile version of a website does not work anymore, on de build version prior v117.5938 like the v116.5845 its work fine.

i use the the versions on 3 different Devices like Samsung S9+, Samsung Tablet S5E and Surface Duo using Android 10,11 and 12 L they all have the same problem.

**Comment by macchrome** [comment] 2023-09-30 18:41
Reproducable

Seems to be related to this problem:  https://github.com/uazo/cromite/issues/222

Won't be fixed in this version.

**Closed as completed by macchrome** 2023-09-30 18:41 UTC
